import { memo } from "react"

const dataSource = [
  {
    quarter: 1,
    desc: "数千万次感受遥遥领先",
    heart: "慧心",
    title: "智慧之心",
    subtitle: "助庆新春佳节",
    votename: "华为",
    cardname: "华为新春",
    aid: 7894172120,
    cid: 7894172120,
    name: "华为终端",
    creative: {
      crt_size: 1814,
    },
  },
  {
    quarter: 1,
    desc: "数万人为自然之美点赞",
    heart: "赏心",
    title: "赏心悦目",
    subtitle: "看花开五彩绚烂",
    votename: "GUCCI",
    cardname: "GUCCI新春",
    aid: 7579277761,
    cid: 7579277761,
    name: "GUCCI",
    creative: {
      crt_size: 1814,
    },
  },
  {
    quarter: 1,
    desc: "数十万人为安全感点赞",
    heart: "初心",
    title: "不忘初心",
    subtitle: "跟罗翔感受安全",
    votename: "沃尔沃",
    cardname: "沃尔沃",
    aid: 7695390804,
    cid: 7695390804,
    name: "沃尔沃汽车",
    creative: {
      crt_size: 599,
    },
  },
  {
    quarter: 1,
    desc: "数千万次欣赏精致珠宝",
    heart: "赏心",
    title: "赏心悦目",
    subtitle: "共享璀璨时光",
    votename: "宝格丽",
    cardname: "宝格丽",
    aid: 7703459622,
    cid: 7703459622,
    name: "BVLGARI宝格丽",
    creative: {
      crt_size: 1814,
    },
  },
  {
    quarter: 1,
    desc: "过千万次浏览圣罗兰新品",
    heart: "赏心",
    title: "赏心悦目",
    subtitle: "尽显真我本色",
    votename: "圣罗兰",
    cardname: "圣罗兰",
    aid: 7768762385,
    cid: 7768762385,
    name: "SAINTLAURENT圣罗兰",
    creative: {
      crt_size: 666,
    },
  },
  {
    quarter: 1,
    desc: "数千万次观看拜年祝福",
    heart: "暖心",
    title: "暖心满满",
    subtitle: "“杨洋”送喜气",
    votename: "可口可乐",
    cardname: "可口可乐",
    aid: 7812234509,
    cid: 7812234509,
    name: "可口可乐",
    creative: {
      crt_size: 1814,
    },
  },
  {
    quarter: 1,
    desc: "数十万人为沈腾点赞",
    aid: 7865906724,
    cid: 7865906724,
    name: "特仑苏",
    heart: "暖心",
    title: "暖心满满",
    subtitle: "相信更好的力量",
    votename: "特仑苏",
    cardname: "特仑苏沈腾",
    creative: {
      crt_size: 599,
    },
  },
  {
    quarter: 1,
    desc: "过十万次点击领取福运",
    aid: 7893176164,
    cid: 7893176164,
    name: "希尔顿Hilton",
    votename: "希尔顿",
    cardname: "希尔顿",
    title: "玩心无限",
    subtitle: "福运连连看",
    heart: "玩心",
    creative: {
      crt_size: 1708,
    },
  },
  {
    quarter: 1,
    desc: "过百万次点击了解捷达",
    heart: "暖心",
    title: "暖心满满",
    subtitle: "祝福永远不嫌多",
    votename: "捷达",
    cardname: "捷达",
    aid: 7902071700,
    cid: 7902071700,
    name: "JETTA捷达",
    creative: {
      crt_size: 698,
    },
  },
  {
    quarter: 1,
    desc: "腕表细节曾获过万留言",
    heart: "赏心",
    title: "赏心悦目",
    subtitle: "精致恒久卓越",
    votename: "劳力士",
    cardname: "劳力士",
    aid: 8899137259,
    cid: 8899137259,
    name: "ROLEX劳力士",
    creative: {
      crt_size: 1708,
    },
  },
  {
    quarter: 2,
    desc: "过千万次看霆锋解锁科技",
    heart: "慧心",
    title: "智慧之心",
    subtitle: "领会纯净节奏",
    votename: "戴森",
    cardname: "戴森耳机",
    aid: 9182701045,
    cid: 9182701045,
    name: "Dyson戴森",
    creative: {
      crt_size: 698,
    },
  },
  {
    quarter: 2,
    desc: "过千万次观看郭帆大片",
    heart: "创心",
    title: "创心百变",
    subtitle: "用一念创造明天",
    votename: "ROG",
    cardname: "ROG",
    aid: 9675669949,
    cid: 9675669949,
    name: "ROG玩家国度俱乐部",
    creative: {
      crt_size: 599,
    },
  },
  {
    quarter: 2,
    desc: "全新探歌获过万次留言",
    heart: "随心",
    title: "随心前行",
    subtitle: "点亮生活新鲜感",
    votename: "一汽大众",
    cardname: "一汽大众",
    aid: 9786921157,
    cid: 9786921157,
    name: "一汽大众汽车",
    creative: {
      crt_size: 599,
    },
  },
  {
    quarter: 2,
    desc: "一博收到了过万次留言",
    heart: "创心",
    title: "创心百变",
    subtitle: "一博痛快畅饮",
    votename: "康师傅",
    cardname: "康师傅",
    aid: 9834152276,
    cid: 9834152276,
    name: "康师傅冰红茶冰力十足",
    creative: {
      crt_size: 698,
    },
  },
  {
    quarter: 2,
    desc: "数万人为吴磊新ID点赞",
    heart: "随心",
    title: "随心前行",
    subtitle: "ID 多姿多彩",
    votename: "上汽大众",
    cardname: "上汽大众吴磊",
    aid: 9924927234,
    cid: 9924927234,
    name: "上汽大众大众品牌",
    creative: {
      crt_size: 698,
    },
  },
  {
    quarter: 2,
    desc: "数万人点赞连结肖战爱意",
    heart: "赏心",
    title: "赏心悦目",
    subtitle: "肖战让爱意加乘",
    votename: "GUCCI",
    cardname: "GUCCI肖战",
    aid: 9950478178,
    cid: 9950478178,
    name: "GUCCI",
    creative: {
      crt_size: 666,
    },
  },
  {
    quarter: 2,
    desc: "数万人为青春纯真点赞",
    heart: "初心",
    title: "不忘初心",
    subtitle: "一起回归纯与真",
    votename: "纯甄",
    cardname: "纯甄",
    aid: 9955234152,
    cid: 9955234152,
    name: "纯甄",
    creative: {
      crt_size: 599,
    },
  },
  {
    quarter: 2,
    desc: "数十万人为生活细节点赞",
    heart: "暖心",
    title: "暖心满满",
    subtitle: "记录生活点滴",
    votename: "小米",
    cardname: "小米张颂文",
    aid: 9958846053,
    cid: 9958846053,
    name: "小米公司",
    creative: {
      crt_size: 720,
    },
  },
  {
    quarter: 2,
    desc: "数万次留言鼓励高三学子",
    heart: "创心",
    title: "创心百变",
    subtitle: "活力迎接每天",
    votename: "雀巢",
    cardname: "雀巢",
    aid: 9983050693,
    cid: 9983050693,
    name: "雀巢中国",
    creative: {
      crt_size: 599,
    },
  },
  {
    quarter: 3,
    desc: "数十万次与猫咪可爱互动",
    heart: "萌心",
    title: "宠爱萌心",
    subtitle: "快被猫咪萌翻啦",
    votename: "戴森",
    cardname: "戴森吸尘器",
    aid: 11478178934,
    cid: 11478178934,
    name: "Dyson戴森",
    creative: {
      crt_size: 698,
    },
  },
  {
    quarter: 3,
    desc: "数万人为肖战点赞",
    heart: "初心",
    title: "不忘初心",
    subtitle: "与肖战举杯同饮",
    votename: "青岛啤酒",
    cardname: "青岛啤酒",
    aid: 11500775448,
    cid: 11500775448,
    name: "青岛啤酒官方服务号",
    creative: {
      crt_size: 1065,
    },
  },
  {
    quarter: 3,
    desc: "数十万次点击了解宇宙",
    heart: "初心",
    title: "不忘初心",
    subtitle: "以科技感受美好",
    votename: "小米",
    cardname: "小米撒贝宁",
    aid: 11592256520,
    cid: 11592256520,
    name: "小米公司",
    creative: {
      crt_size: 720,
    },
  },
  {
    quarter: 3,
    desc: "过万人为舒淇美颜点赞",
    heart: "赏心",
    title: "赏心悦目",
    subtitle: "舒淇爱不释手",
    votename: "OPPO",
    cardname: "OPPO",
    aid: 11920565985,
    cid: 11920565985,
    name: "OPPO",
    creative: {
      crt_size: 2177,
    },
  },
  {
    quarter: 3,
    desc: "过千万次围观美酒加咖啡",
    heart: "创心",
    title: "创心百变",
    subtitle: "跨界联名够出圈",
    votename: "瑞幸",
    cardname: "瑞幸",
    aid: 11966796851,
    cid: 11966796851,
    name: "luckincoffee瑞幸咖啡",
    creative: {
      crt_size: 599,
    },
  },
  {
    quarter: 3,
    desc: "数百万次看A7L打破边界",
    heart: "初心",
    title: "不忘初心",
    subtitle: "穿梭风雨之间",
    votename: "上汽奥迪",
    cardname: "上汽奥迪",
    aid: 11984505491,
    cid: 11984505491,
    name: "上汽奥迪",
    creative: {
      crt_size: 1708,
    },
  },
  {
    quarter: 3,
    desc: "数百万次围观开园盛事",
    heart: "玩心",
    title: "玩心无限",
    subtitle: "同游宇宙奇观",
    votename: "长隆",
    cardname: "长隆",
    aid: 12211700207,
    cid: 12211700207,
    name: "长隆旅游",
    creative: {
      crt_size: 1708,
    },
  },
  {
    quarter: 3,
    desc: "数万人为运动美学点赞",
    heart: "创心",
    title: "创心百变",
    subtitle: "澎湃挥洒而至",
    votename: "保时捷",
    cardname: "保时捷",
    aid: 12245993162,
    cid: 12245993162,
    name: "保时捷中国",
    creative: {
      crt_size: 2177,
    },
  },
  {
    quarter: 3,
    desc: "长鹅收到过万次搞怪互动",
    heart: "萌心",
    title: "宠爱萌心",
    subtitle: "长鹅伴你成长",
    votename: "腾讯",
    cardname: "腾讯长鹅",
    aid: 12316375234,
    cid: 12316375234,
    name: "腾讯",
    creative: {
      crt_size: 599,
    },
  },
  {
    quarter: 4,
    desc: "过千万次播放王耀庆演出",
    heart: "玩心",
    title: "玩心无限",
    subtitle: "“舅”那么搞怪",
    votename: "上汽大众",
    cardname: "上汽大众王耀庆",
    aid: 12341881067,
    cid: 12341881067,
    name: "上汽大众大众品牌",
    creative: {
      crt_size: 599,
    },
  },
  {
    quarter: 4,
    desc: "数十万人为费翔点赞",
    heart: "初心",
    title: "不忘初心",
    subtitle: "始终心系故乡",
    votename: "小米",
    cardname: "小米费翔",
    aid: 12617720859,
    cid: 12617720859,
    name: "小米公司",
    creative: {
      crt_size: 720,
    },
  },
  {
    quarter: 4,
    desc: "过万人为无损音质点赞",
    heart: "慧心",
    title: "智慧之心",
    subtitle: "静听真切心声",
    votename: "华为",
    cardname: "华为耳机",
    aid: 12706922593,
    cid: 12706922593,
    name: "华为终端",
    creative: {
      crt_size: 599,
    },
  },
  {
    quarter: 4,
    desc: "过万人为二手玫瑰点赞",
    heart: "玩心",
    title: "玩心无限",
    subtitle: "整出给力花活",
    votename: "英特尔",
    cardname: "英特尔",
    aid: 12782360404,
    cid: 12782360404,
    name: "英特尔中国",
    creative: {
      crt_size: 1765,
    },
  },
  {
    quarter: 4,
    desc: "梁朝伟收到过十万次留言",
    heart: "随心",
    title: "随心前行",
    subtitle: "坐上未来的座驾",
    votename: "阿维塔",
    cardname: "阿维塔",
    aid: 12890123397,
    cid: 12890123397,
    name: "阿维塔",
    creative: {
      crt_size: 2177,
    },
  },
  {
    quarter: 4,
    desc: "过千万次观看直发黑科技",
    heart: "慧心",
    title: "智慧之心",
    subtitle: "简直一步到位",
    votename: "戴森",
    cardname: "戴森直发器",
    aid: 13128856624,
    cid: 13128856624,
    name: "Dyson戴森",
    creative: {
      crt_size: 599,
    },
  },
  {
    quarter: 4,
    desc: "过百万人点燃新年烟花",
    heart: "暖心",
    title: "暖心满满",
    subtitle: "新年乐事有你",
    votename: "乐事",
    cardname: "乐事",
    aid: 13221262014,
    cid: 13221262014,
    name: "乐事",
    creative: {
      crt_size: 599,
    },
  },
  {
    quarter: 4,
    desc: "靳东收到数万次留言",
    heart: "暖心",
    title: "暖心满满",
    subtitle: "温暖笑对寒冬",
    votename: "特仑苏",
    cardname: "特仑苏靳东",
    aid: 13497922323,
    cid: 13497922323,
    name: "特仑苏",
    creative: {
      crt_size: 2177,
    },
  },
  {
    quarter: 4,
    desc: "数十万人为易烊千玺点赞",
    heart: "随心",
    title: "随心前行",
    subtitle: "回归更好当下",
    votename: "特仑苏",
    cardname: "特仑苏千玺",
    aid: 13504128298,
    cid: 13504128298,
    name: "特仑苏",
    creative: {
      crt_size: 599,
    },
  },
]

const ScrollItem = memo(
  ({ deg, index, active }: { deg: number; index: number; active: boolean }) => {
    const item = dataSource[index]

    return (
      <div
        className="scroll-item"
        key={deg}
        data-index={index}
        data-rotate={deg}
        style={{
          // @ts-ignore
          "--rotate": `${deg}deg`,
        }}
      >
        <div
          className="scroll-item-inner"
          style={{
            filter: "saturate(0.75)",
            backgroundImage: `url(https://wxa.wxs.qq.com/wxad-design/yijie/bm28-0119/${item.cid}.webp)`,
            backgroundSize: "100% auto",
            backgroundRepeat: "no-repeat",
            transform: active ? "scale(0.95)" : "scale(1)",
            transition: ".5s ease all",
          }}
        />
      </div>
    )
  }
)

export default ScrollItem
